---
blank_issues_enabled: false

contact_links:
  - name: "Espressif GitHub"
    url: "https://github.com/espressif"
    about: "Espressif's GitHub repositories"

  - name: "Espressif Homepage"
    url: "https://www.espressif.com"
    about: "About the company"
